travis:
  secure:
    BINSTAR_TOKEN: TKaJbONyfMdheNX47o3ynKSujVq8E7pnSkTDzvp8VnYuKZelliLkhSvv1uoo17nBwqUNKGPzX35tQzNIIBMlZOlI5gOvyIDnUMQdI8fL6AOwdhMq/epuxBqae2ZrfbXZZ1Cs8revPxtZ0Wm6FdmxBeQ8Auc40pR/ANWSdpl2cwRjLCFnt7PJMxRU3UzoAGSHxbOwYxWM4PoM0E+6hkEj8c3rGw4S86gECJzRXljki9nHuRbn/5d2weeG4Lk5qVAE1umtm1xFaO/+ueLEUuM+wf2s2p7yvCFWQsvL5iqnExdAFgF2lgA5vi5NuoY6RWLQTXdoAOunVc6jHXKHSc6Bn5sA9VCQ8MkDddGT3Z026j7UW3SBaNI9p7rl1a+aOv+WOKUoG/yu+9DiAdDxfVb56O+M2amlSKKOZHn3j5r2X585FV6SjJO95t4zC1z3F7nF1di5ocOsM1DEbDkO8GI5P1nSYbLhQHIZi64PEZWg+FPjg758ptgJyIe52EiNPlmbvpB3O9M0dinZn8ufwhdJelBTX9fiLJ5K4HLy+PfGIMHlarvsheTa/Y6HSAACb8vo7xA4LzmvyYVc5ipe2xHf7PJAJdhHgprWceZyp5zqQ6lEdwyPFE0iuovhO4YtjUH6uUn4GQP1pH038qYJ2PI1moIyO86Bd32DeRhC3QkkxFA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
